### PR TITLE
integration with chieffancypants / angular-loading-bar

### PR DESCRIPTION
**Pull request by maurosala**
integration with chieffancypants / angular-loading-bar
https://github.com/chieffancypants/angular-loading-bar

### CODE REVIEW

**Comment by devnixs** [comment]
Hi Maurosala,
Thanks for your help.
Can you show an example to how to use it?
Or better, write a test that uses it.

Thanks!

**Comment by maurosala** [comment]
When you import "angular-loading-bar" every call will be intercepted and progress bar will be displayed
If you don't need this in odata call you can specify
ignoreLoadingBar: false

here a working example
https://jsfiddle.net/maurosala/fh1xs38o/1/

**Comment by devnixs** [comment]
I can't get your example working : 
http://i.imgur.com/t4an0UW.png

**Comment by maurosala** [comment]
You need to go here
[https://cdn.maurosala.it/odataresources.js](https://cdn.maurosala.it/odataresources.js)
and here
[https://services.odata.org/V4/OData/OData.svc/](https://services.odata.org/V4/OData/OData.svc/)
from your browser, accept the security certificate and then go to jsfiddle.
The problem is that google chrome can't accept SSL certificate from my CDN and odata.org until you accept go to the page and you bypass it
sorry

**Pull request merged**
