### PR TITLE
ODataProvider.format method & ODataResource odatakey complex key support & ExpandPredicate

### PR DESCRIPTION
**Pull request by kyse**

### CODE REVIEW

**Comment by devnixs** [comment]
Hi Kyse, 
Thanks for your help!
But it would even more awesome if you could write a couple of tests to show us how to use what you did. Let me know if you need any help about where to put them or how to run them!
Raphael

**Comment by kyse** [comment]
Hey Raphael, will do my best.  I wrote one (not sure I put it in the right
place) for the complex key support, will add one for the format filter.

I have another extension where I created a linq-ish recursive expand engine
that adds support for embedded select's.  Trying to figure out how to fit
it in with what you have, at the moment it's more hackish to accomplish my
goal.  I've attached it if you have time to give your thoughts.  if you
like it, I'll throw it in another pull request.

**Comment by devnixs** [comment]
Hi Kyse,

I use the file specs/ODataTest.js for small unit tests that applies on the component level.
I use the file specs/ODataResourcesTest.js for more like integration tests when I want to test the whole thing.

Thanks!

**Comment by kyse** [comment]
Not sure why coveralls is still complaining about my three throws.  I added checks in for them, perhaps you can shed some light on what I'm doing wrong.

**Comment by kyse** [comment]
Hopefully that covers everything.

**Comment by devnixs** [comment]
Just reviewed what you did. Wow it's really cool! Thanks for your help!

**Pull request merged**
